on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04
      #options: --network host
      #ports: [33333]

    services:
      mongo:
        image: mongo:8.0
        ports:
          - 27017:27017

    steps:
      - run: apt update

      - run: |
          apt install -y iproute2
          ss -a

      - run: |
          apt install -y npm
          npm install -g mongosh
          mongosh --host mongo --port 27017 --eval "db.serverStatus()"
